apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaling-operator
  namespace: web_app
subjects:
  - kind: ServiceAccount
    name: scaling-operator
    namespace: web_app
roleRef:
  kind: Role
  name: scaling-operator
  apiGroup: rbac.authorization.k8s.io