apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaling-operator
  namespace: web_app
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["teamsnap.com"]
    resources: ["scalingresources"]
    verbs: ["get", "list", "watch", "update"]