apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scalingresources.teamsnap.com
spec:
  group: teamsnap.com
  names:
    plural: scalingresources
    singular: scalingresource
    kind: ScalingResource
    shortNames:
    - sr
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              scalePercentage:
                type: number
              scheduleTime:
                type: string
              duration:
                type: string
              targetDeployment:
                type: string
            required:
            - scalePercentage
            - scheduleTime
            - duration
            - targetDeployment